===  aPPENDIX

=== Revision History



=== Early Draft 1 (dated 06/06/2005)

=== Significant Changes in Public Draft (dated 08/15/2006).

=== Changes to API

The classes and interfaces of the API were
divided into four packages, message, config, callback, and module.

The MessageLayer Interface was removed. Message
layers are represented as a String.

The use of the URI type to identify
applications (and other things) was replaced by String,

The AuthParam Interface was replaced by the
MessageInfo Interface, and concrete message-specific implementations of
the AuthParam interface were removed from the SPI.

The disposeSubject methods were renamed
cleanSubject.

The sharedMap arguments were removed.
MessageInfo is now used to convey such context.

The parameter names corresponding to subjects
were modified to correspond to the service role of the corresponding
party (i.e., client or server) as 0pposed to the message sending role.

The ModuleProperties Interface was removed, and
the responsibility for implementing transactional semantics was
transferred to the authentication context (if it supports multiple
sufficient alternatives).

The PendingException and FailureException
classes were removed and a new return value type, AuthStatus, was
defined to convey the related semantics. A general return value model
was provided by the AuthStatus class.

The AuthConfigProvider interface was created to
facilitate the integration of alternative module conversation systems,
and facilities were added to the AuthConfigFactory to support the
registration of AuthConfigProviders. The RegistrationListener interface
we defined to support live replacement of configuration systems.

The authentication context configuration layer
was formalized and methods to acquire authentication contexts (i.e,
getAuthContext) were moved to the authentication context configuration
layer. Subject arguments were added to the getAuthContext methods to
support both the acquisition of credentials by the config system, and to
allow the Subject and its content to factor in the context acquisition.

new callbacks were defined (i.e.
CallerPrincipalCallback and GroupPrincipalCallback).

=== Changes to Processing Model

The AuthStatus return model was described and
the message processing model of the Overview and Message Authentication
chapters was evolved to describe the processing by runtimes of the
returned AuthStatus values, especially in the case of a multi-message
authentication dialog.

=== Changes to Profiles

The Servlet, SOAP, and JMS profiles were added.

=== Changes in Proposed Final Draft 1

=== Changes to Preface

Changed Status and Audience to reflect
transition to PFD.

Added paragraphs to describe relationship to
JAAS

== CHAPTER 7 - 

Changed
sectionslink:jaspic.html#a166[See Acquire AuthContext
Identifier] and link:jaspic.html#a172[See Acquire
Authentication Context] to reflect change in AuthConfig interface from
getOperation to getAuthContextID.

Added definition of “message processing
runtime” to link:jaspic.html#a194[See Terminology]” section.

== CHAPTER 8 - 

Changed sections
link:jaspic.html#a265[See Authentication],
link:jaspic.html#a285[See What the Provider Must Do],
link:jaspic.html#a290[See Acquire AuthContext Identifier],
link:jaspic.html#a297[See Acquire Authentication Context]o
reflect change in AuthConfig interface from getOperation to
getAuthContextID.

to link:jaspic.html#a274[See What the
Runtime Must Do]”, added a requirement that runtimes support the
granting to applications and administration utilities of the permissions
required to employ the configuration interfaces of the SPI.

In subsection “at point (1) in the message
processing model:” of link:jaspic.html#a317[See What the
Runtime Must Do]”, clarified clientSubject requirements, and indicated
that a non-null clientSubject must not be read-only.

In subsection “at point (4) in the message
processing model:” of link:jaspic.html#a317[See What the
Runtime Must Do]”, clarified serviceSubject requirements, and indicated
that a non-null serviceSubject must not be read-only.

added “Fig 2.1: State Diagram of Client Message
Processing Runtime”

In subsection “at point (2) in the message
processing model:” of link:jaspic.html#a317[See What the
Runtime Must Do]”, clarified serviceSubject requirements, and indicated
that a non-null serviceSubject must not be read-only.

In subsection “at point (3) in the message
processing model:” of link:jaspic.html#a317[See What the
Runtime Must Do]”, clarified that the call to secureResponse should be
made independent of the outcome of the application request processing.

added “Fig 2.2: State Diagram of Server Message
Processing Runtime”.

== CHAPTER 9 - 

Added last sentence to introductory paragraph
to clarify what is required to be a compatible implementation of the
profile.

In link:jaspic.html#a371[See
Application Context Identifier]”, extended identifier format to include
the logical hostname along with he context path.

In link:jaspic.html#a381[See
CallbackHandler Requirements]”, added requirement that the handler
argument (passed by the runtime) must not be null.

Changed section
link:jaspic.html#a396[See Authentication Context Requirements]
to reflect change in AuthConfig interface from getOperation to
getAuthContextID.

Changed link:jaspic.html#a400[See
Authentication Context Identifiers]”, to remove requirements for a
specific identifier format.

Changed link:jaspic.html#a404[See
Module Initialization Properties]”,to require that the runtime set the
PolicyContext in the module initialization properties passed to
getAuthContext call.

In link:jaspic.html#a412[See
MessagePolicy Requirements]”, removed requirements relating to
responsePolicy. Also moved responsibility for determining when (client)
authentication is required from the AuthConfig subsystem to the message
processing runtime.

In link:jaspic.html#a418[See Message
Processing Requirements]”, clarified the points within the servlet
processing model that corresponding to points 2 and 3 of the message
module. Added explicit statement to ensure that validateRequest is
called on all requests including requests to a login form. Moved the
comment regarding “delegation of session management” to a footnote.
Changed the processing when there is an authorization failure to require
that secureResponse be called. Changed the prohibition on calling
secureResponse when the application throws an exception to a
recommendation. Added last sentence to require the use of the principal
established using the CallerPrincipalCallback where identity propagation
is configured.

Changed link:jaspic.html#a425[See
MessageInfo Requirements]”, to conditionally require the inclusion of a
property within the MessageInfo map when client authentication is
required. Also placed new requirement on the authentication context
configuration system that is use this value to establish the
requestPolicy.

Added initial sentence to
link:jaspic.html#a440[See ServerAuth Processing]”, to reiterate
that validateRequest be called on every request that satisfies the
applicable connection requirements.

In link:jaspic.html#a442[See
validateRequest Before Service Invocation]”,moved responsibility for
coordinating disparate uses of the CallerPrincipalCallback to the
context. Relaxed prohibition on returning SEND_CONTINUE from modules
initialized with an optional requestPolicy by allowing modules to
continue a multi-message authentication dialog as long as it was
initiated by the client. Added requirement that modules initialized with
an optional requestPolicy, use the CallerPrincipalCallback to
established an unauthenticated caller identity (if they return
AuthStatus.SUCCESS without having satisfied the TargetPolicy).

In link:jaspic.html#a449[See
validateRequest After Service Invocation]”, removed requirement that the
module set the HTTP 200 (OK) status code.

In link:jaspic.html#a455[See
secureResponse Processing]”, removed requirements dependent on
responsePolicy.

Replaced section “Dealing with Servlet Commit
Semantics” with a new link:jaspic.html#a459[See Wrapping and
UnWrapping of Requests and Responses].

== CHAPTER 10 - 

Added last sentence to introductory paragraph
to clarify what is required to be a compatible implementation of the
profile.

Changed link:jaspic.html#a507[See
Application Context Identifier]”, to refer to subsections within the
sub-profiles where the corresponding identifiers are defined.

In link:jaspic.html#a514[See
CallbackHandler Requirements]”, added requirement that the handler
argument (passed by the runtime) must not be null.

In link:jaspic.html#a526[See
Authentication Context Requirements]”, added clarification of what it
means when getAuthContext returns a null value, and how the value
returned by getAuthContext impacts support for a session oriented
authentication mechanism.

Changed link:jaspic.html#a531[See
Authentication Context Identifiers]”, to remove requirements for a
specific identifier format.

Added new link:jaspic.html#a537[See
Client-Side Application Context Identifier]”, to describe the identifier
format as the concatenation of a client scope identifier and a client
reference to the service. For client scope identifiers, recommended the
use of application identifiers where they are available and suggested
the use of the archive URI where application identifiers are not
available. Required that the service-ref name be used (if available) for
the client reference to the service. Otherwise the service URL is to be
used. Included examples, and added a last paragraph indicating that
registration would require an ability to predict the client scope
identifier and client service reference associated by the runtime with a
client invocation.

Removed requirements from
link:jaspic.html#a556[See Authentication Context
Requirements]”, that were already stated in
link:jaspic.html#a526[See Authentication Context
Requirements]”.

In link:jaspic.html#a564[See Message
Processing Requirements]”, to account for one-way application message
exchange patterns, limited the circumstances under which a runtime may
proceed to point (4) in the message processing model.

In link:jaspic.html#a568[See
MessageInfo Requirements]”, changed the description of the value of the
javax.xml.ws.wsdl.service property such that it must be a QName
containing the service name. Removed statement of relationship of value
to client authentication context identifier.

In link:jaspic.html#a580[See
secureRequest Processing]”, corrected cut an paste errors (i.e.,
s/response/request/). Relaxed prohibition on returning SEND_CONTINUE
from secureRequest on modules initialized with an optional
requestPolicy. Added requirement that a module must return
AuthStatus.SEND_SUCCESS (from secureRequest) if it was initialized with
a null requestPolicy.

In link:jaspic.html#a590[See
validateResponse After Service Invocation]”, on modules initialized with
and optional responsePolicy, relaxed prohibition on returning
SEND_CONTINUE from validateResponse and clarified the handling of
AuthException and the various AuthStatus return values.

Added new link:jaspic.html#a603[See
Server-Side Application Context Identifier]”, to describe the identifier
format as the concatenation of the logical hostname of the virtual
server, and the service endpoint URI. Also included an example.

Removed requirements from
link:jaspic.html#a616[See Authentication Context
Requirements]”, that were already stated in
link:jaspic.html#a526[See Authentication Context
Requirements]”.

Changed link:jaspic.html#a618[See
Module Initialization Properties]”, to require that PolicyContext be set
in the module initialization properties (passed to getAuthContext call)
if the server runtime is a JSR 115 compatible container.

In link:jaspic.html#a626[See
MessagePolicy Requirements]”, removed paragraphs defining when message
protection is required by an EJB web service container. Added
requirement for a specific TargetPolicy within requestPolicy when the
CallerPrincipalCallback is to be used by the authentication module(s) of
the context. Added a requirement that the requestPolicy must be
mandatory and must include a specific TargetPolicy when all the
operations of an endpoint require client authentication. Added
recommended return values for isMandatory, when not all of the
operations of an endpoint require client authentication.

In link:jaspic.html#a632[See Message
Processing Requirements]”, to account for one-way application message
exchange patterns, limited the circumstances under which a runtime may
proceed to point (3) in the message processing model. Moved the comment
regarding “delegation of session management” to a footnote. Changed the
processing to require that secureResponse be called when there is an
authorization failure. Changed the prohibition on calling secureResponse
when the application throws an exception to a requirement that
secureResponse be called. Added last sentence to require the use of the
principal established using the CallerPrincipalCallback where identity
propagation is configured.

In link:jaspic.html#a642[See
MessageInfo Properties]” removed the requirement that the service name
property be set in the MessageInfo Map.

In link:jaspic.html#a648[See
validateRequest Before Service Invocation]”, moved responsibility for
coordinating disparate uses of the CallerPrincipalCallback to the
context. Relaxed prohibition on returning SEND_CONTINUE from modules
initialized with an optional requestPolicy by allowing modules to
continue a multi-message authentication dialog as long as it was
initiated by the client. Added requirement that modules initialized with
an optional requestPolicy, containing a prescribed TargetPolicy, use the
CallerPrincipalCallback to established an unauthenticated caller
identity (if they return AuthStatus.SUCCESS without having satisfied the
TargetPolicy).

in link:jaspic.html#a662[See
secureResponse Processing]”, corrected the required return value when
responsePolicy == null to be AuthStatus.SEND_SUCCESS.

== CHAPTER 11 - 

Renamed chapter to
link:jaspic.html#a666[See Future Profiles]”.

Changed chapter to be strictly informative;
serving to capture suggestions for additional profiles.

Added link:jaspic.html#a677[See
RMI/IIOP Portable Interceptor Profile]”.

=== Changes to link:jaspic.html#a717[See ApPenDIX], Issues

Added new issue,
link:jaspic.html#a746[See HttpServletResponse Buffering and
Header Commit Semantics], with resolution which was factored into the
Servlet Profile (see link:jaspic.html#a459[See Wrapping and
UnWrapping of Requests and Responses]).

=== Changes to link:jaspic.html#UNKNOWN[See aPPENDIX], API

In javax.security.auth.message.MessagePolicy,
changed name of method “isManadatory” to “isMandatory”.

In
javax.security.auth.message.config.AuthConfig, changed the name of
method “getOperation” to “getAuthContextID” and changed the method
definition to indicate that it returns the authentication context
identifier corresponding to the request and response objects in the
messageInfo argument.

 In
javax.security.auth.message.config.AuthConfigFactory, changed
description of the typical sequence of calls to reflect change of
“getOperation” to “getAuthContextID”. Also changed description to
differentiate registration and self-registration. Added comment to
definition of the setFactory method to make it clear that listeners are
NOT notified of the change to the registered factory. Added a second
form of registerConfigProvider that takes an AuthConfigProvider object
(in lieu of an implementation class and properties Map) and that
performs an in-memory registration as apposed to a persisted
registration. Added support for null registrations. Added the
isPersistent method to the AuthConfigFactory.RegistrationContext
interface.

In
javax.security.auth.message.config.AuthConfigProvider, changed
description of the typical sequence of calls to reflect change of
“getOperation” to “getAuthContextID”. Changed requirement for a “public
one argument constructor” to a “public two argument constructor”, where
the 2nd argument may be used to pass an AuthConfigFactory to the
AuthConfigProvider to allow the provider to self-register with the
factory.

In
javax.security.auth.message.config.ClientAuthConfig, changed method and
parameter descriptions to reflect change of “getOperation” to
“getAuthContextID”.

In
javax.security.auth.message.config.ServerAuthConfig, changed method and
parameter descriptions to reflect change of “getOperation” to
“getAuthContextID”.

In
javax.security.auth.message.callback.PasswordValidationCallback, added a
Subject parameter to the constructor, and a getSubject method to make
the Subject available to the CallbackHandler. Also added a sentence
describing the expected use of the PasswordValidationCallback.

In
javax.security.auth.message.callback.PrivateKeyCallback, added
PrivateKeyCallback.DigestRequest so that private keys may be requested
by certificate digest (or thumbprint). Added a sentence describing the
expected use of the PrivateKeyCallback.

In
javax.security.auth.message.callback.SecretKeyCallback, improved
description of the expected use of the SecretKeyCallback.

=== Changes in Proposed Final Draft 2

=== Changes to License

Revised date to May 5, 2007

=== Changes to Servlet Container Profile

In link:jaspic.html#a418[See Message
Processing Requirements]”, added reference to new section,
link:jaspic.html#a464[See Setting the Authentication Results on
the HttpServletRequest]” to describe requirements for setting the
authentication results.

Added link:jaspic.html#a464[See
Setting the Authentication Results on the HttpServletRequest]” to
capture requirements for setting the user principal, remote user, and
authentication type on the HttpServletRequest.

=== Changes to SOAP Profile

Corrected reference (chapter number) to
“Message Authentication” chapter appearing in the chapter introduction.

Corrected ambiguity in
link:jaspic.html#a510[See Message Requirements]”, to make it
clear that the profile does not require that MessageInfo contain only
non-null request and response objects.

=== Changes to LoginModule Bridge Profile

In link:jaspic.html#a685[See
Processing Model]”, revised the method by which a ServerAuthModule
chooses the entry name passed to the LoginContext constructor. This
change allows a single module implementation to be configured to use
different entry names, and thus different login modules.

In link:jaspic.html#a692[See Standard
Callbacks]”, added requirement that GroupPrincipalCallback be supported
when LoginContext is constructed with Subject.

In link:jaspic.html#a694[See
Subjects]”, added requirement that ServerAuthModule employ
CallerPrincipalCallback using same value as that available to
LoginModule via NameCallback.

=== Changes in Final Release

=== Changes to title page

Corrected JCP version to 2.6

=== Changes to Preface

Changed Status and Audience to reflect
transition to Final Release

Changed “including J2EE containers” to
“including J2EE and Java EE containers”

=== Changes to Overview

Changed “exchanged by J2EE containers” to
“exchanged by J2EE and Java EE containers”

=== Changes to References

Changed “[J2SE Specification]” to “[Java SE 5
Specification]”

=== Changes to Issues

Changed “introduced in J2SE 5.0” to “introduced
in Java SE 5”

=== Changes in Maintenance Release A

=== Changes Effecting Entire Document

Changed document Identifier to Maintenance
Release A. Version identifier remains unchanged at 1.0.

== CHAPTER 12 - 

Clarified definition of baseline compatibility
requirements to more explicitly convey that the API is intended to have
more general applicability than the specific contexts of its use defined
within the specification.

=== Changes to link:jaspic.html#UNKNOWN[See aPPENDIX], API

In
javax.security.auth.message.callback.CallerPrincipalCallback, modified
callback definition to allow for principal mapping to occur during the
handling of the callback by the CallbackHandler.

=== Changes in Maintenance Release B

=== Changes Effecting Entire Document

Changed document Identifier to Maintenance
Release B, and Version identifier changed to 1.1.

Updated JCP version to 2.7

Updated the license

Replaced Sun logo with Oracle logo

Removed paragraph tags from PDF bookmarks

=== Changes to Preface

Changed Status to Maintenance Release B version
1.1

Added Will Hopkins, Tim Quinn, Arjan Tijms, and
Yi Wang to the list of contributors

=== Changes to Servlet Container Profile

In link:jaspic.html#a371[See
Application Context Identifier]”, described use of
ServletContext.getVirtualServerName in application context identifier.

In link:jaspic.html#a418[See Message
Processing Requirements]” and link:jaspic.html#a440[See
ServerAuth Processing]”, clarified that validateRequest must be called
on every request for which the Servlet security model applies. Also
included footnote whose text describes that the security model does not
apply to forwards and includes.

 In link:jaspic.html#a442[See
validateRequest Before Service Invocation]”, added clarification to
description of processing for SEND_CONTINUE, especially to allow for
forwards to a login page within an authentication module.

 In link:jaspic.html#a442[See
validateRequest Before Service Invocation]”, clarified description of
processing for SEND_FAILURE to indicate that this return status is
returned when the validation failed and the client should not continue
or retry the request.

Added footnote on header of
link:jaspic.html#a449[See validateRequest After Service
Invocation]” to clarify that “after the service invocation” effectively
means after the call to secureResponse, so as to remain distinct from
the case where a call to authenticate from within the application
results in a call to validateRequest during the service invocation.

Added link:jaspic.html#a457[See
Forwards and Includes by Server Authentication Modules]”, to make it
clear that authentication modules must be able to use a
RequestDispatcher to forward to a login page (for example).

In link:jaspic.html#a464[See Setting
the Authentication Results on the HttpServletRequest]”, amended
description to make this section suitable for describing both the case
where validateRequest is called prior to a request, and the case where
validateRequest is (presumably) being called during the processing of
the request

In link:jaspic.html#a464[See Setting
the Authentication Results on the HttpServletRequest]”, added
link:jaspic.html#a473[See Authentication Session Registration
(Callback) Property] to define the name of the session registration
callback property. Also added description of the processing of the
property.

Added link:jaspic.html#a479[See
Sub-profile for authenticate, login, and logout of HttpServletRequest]”
to define the use of the JASPIC SPI under
HttpServletRequest.authenticate, login, and logout.

=== Changes to link:jaspic.html#a717[See ApPenDIX], Issues

Added link:jaspic.html#a749[See
Reporting New Issues]Reporting New Issues” with inks to java.net project
and JIRA issue tracker.

=== Changes to link:jaspic.html#UNKNOWN[See aPPENDIX], SPI

In abstract
link:jaspic.html#UNKNOWN[See AuthConfigFactory]” class, made
public the static permissions that are used to protect the static
getFactory and setFactory methods, and improved documentation so users
of the SPI can know which permissions are used. Also added and
additional public providerRegistrationSecurityPermission and required
that it be used by factory implementations to protect methods like
registerConfigProvider. Removed incorrect assertion from javadoc of
getFactory, both forms of registerConfigProvider, and refresh, that
checked AuthException could be thrown (by these methods). Changed the
javadoc of these four methods to indicate that the conditions for which
they were expected to throw an AuthException should instead be handled
within their existing declarations of throwing an (unchecked)
SecurityException. Regenerated (mif) javadocs (embedded in spec) from
html javadocs, which corrected definition for layer and appContext
parameters of link:jaspic.html#UNKNOWN[See
getConfigProvider(java.lang.String layer, java.lang.String appContext,
RegistrationListener145 listener)].

In link:jaspic.html#UNKNOWN[See
AuthConfig]”, and link:jaspic.html#UNKNOWN[See
AuthConfigProvider]” interfaces, removed incorrect assertion from
javadoc of refresh method that checked AuthException could be thrown,
and changed javadoc to indicate that the conditions for which refresh
was expected to throw an AuthException should instead be handled within
its existing declaration of throwing an (unchecked) SecurityException.



'''''

[.footnoteNumber]# 1.# [[a898]]The dashed lines
between validateRequest and validateResponse convey additional message
exchanges that may occur when message validation requires a
multi-message dialog, such as would occur in challenge-response
protocols.

[.footnoteNumber]# 2.# [[a899]]A client runtime may
be able to tell when a request is the same, based on the context (for
example, stub) from which the request is made.

[.footnoteNumber]# 3.# [[a900]]For example, where the
message content that defines the identifier is encrypted.

[.footnoteNumber]# 4.# [[a901]]The application
request processing must not be performed if the request authorization
fails. If the runtime intends to return a response message to indicate
the failed authorization, the profile of this specification being
followed by the runtime must establish whether or not secureResponse
must be called prior to sending the authorization failure message.

[.footnoteNumber]# 5.# [[a902]]validateRequest is
called to process all received messages, including security
mechanism-specific messages sent by clients in response to service
response messages.

[.footnoteNumber]# 6.# [[a903]]In a JSR 115
environment, connection requirements are tested by checking a
WebUserDataPermission constructed with the HttpServletRequest. In a
non-JSR 115 environment, connection requirements are tested by comparing
the security properties of the connection on which the request was
received with the permitted connection types as defined through
user-data-constraints in the corresponding web.xml.

[.footnoteNumber]# 7.# [[a904]]In a JSR 115
environment, authorization requirements are enforced by checking if the
authenticated caller identity (such as it is) has been granted the
WebResourcePermission corresponding to the HttpServletRequest. In a
non-JSR 115 environment, authorization requirements are enforced by
checking if the role-mappings of the authenticated caller identity are
sufficient to satisfy the auth-constraints (if any) that apply to the
request as defined in the corresponding web.xml.

[.footnoteNumber]# 8.# [[a905]]These unconditional
calls to validateRequest are necessary to allow for delegation of
servlet authentication session management to authentication contexts and
their contained authentication modules.

[.footnoteNumber]# 9.# [[a906]]Note that Servlet
security model does not apply when a servlet uses a RequestDispatcher to
invoke a static resource or servlet using a forward or an include.

[.footnoteNumber]# 10.# [[a907]]If the
auth-constraint is an excluding auth-constraint (that is, an
auth-constraint that authorizes no roles), the Servlet Specification
requires that no access be permitted independent of authentication.
Runtimes should reject requests to excluded resources prior to
proceeding to point (2) in the message processing model (that is, prior
to the authentication processing).

[.footnoteNumber]# 11.# [[a908]]JSR 115 compatible
runtimes should also reject requests to excluded resources prior to
proceeding to point (2) in the message processing model (that is, prior
to the authentication processing).

[.footnoteNumber]# 12.# [[a909]]The module may
continue, or refresh an authentication dialog that has already been
initiated (perhaps by the client) in the request, but it must not start
an authentication dialog for a request which has not yet been associated
with authentication information (as understood by the module).

[.footnoteNumber]# 13.# [[a910]]“After the service
invocation” effectively means after the first call to secureResponse; as
distinct from the case where authenticate might call validateRequest
from within the service invocation and before it completes.

[.footnoteNumber]# 14.# [[a911]]Except when
getUserPrincipal returns null; in which case the value returned by
getRemoteUser must be null

[.footnoteNumber]# 15.# [[a912]]Unlike
CallbackHandler processed Callback objects, callback properties are not
acted upon until the authentication module returns to the runtime.

[.footnoteNumber]# 16.# [[a913]]Note that the
authenticate method must not perform the pre-dispatch container
authorization check that the message processing runtime would typically
perform on successful return from validateRequest.

[.footnoteNumber]# 17.# [[a914]]The module may
continue, or refresh an authentication dialog that has already been
initiated (perhaps by the client) in the request, but it must not start
an authentication dialog for a request which has not yet been associated
with authentication information (as understood by the module).

[.footnoteNumber]# 18.# [[a915]]Occurs when the
module is challenged by the server during secureRequest processing.

[.footnoteNumber]# 19.# [[a916]]For an http or https
schema, the path must be the corresponding component of the "generic
URI" syntax (that is, <scheme>://<authority><path>?<query>) described in
section 3. of RFC 2396 "Uniform Resource Identifiers (URI): Generic
Syntax". If the service is implemented as a Servlet, the path must begin
with the context-path.

[.footnoteNumber]# 20.# [[a917]]This authorization
processing would NOT be expected to include the enforcement of Servlet
Auth-Constraints since they are defined at url-pattern granularity.

[.footnoteNumber]# 21.# [[a918]]The module may
continue, or refresh an authentication dialog that has already been
initiated (perhaps by the client) in the request, but it must not start
an authentication dialog for a request which has not yet been associated
with authentication information (as understood by the module).

[.footnoteNumber]# 22.# [[a919]]Occurs when the
module is challenged by the client during secureResponse processing.

[.footnoteNumber]# 23.# [[a920]]The
CallerPrincipalCallback may be constucted with a String argument
containing the name value, or with a Principal argument whose getName
method returns the name value.

[.footnoteNumber]# 24.# [[a921]]Some
HttpServletResponse implementations extend the buffering methodology to
the response headers, such that the status code and the first buffers
worth of response headers are sent when when the header buffer is full.
This does not, strictly speaking, cause the response to be committed,
but instead creates a situation where attempts to change the status
code, or to replace an existing header, would not be expected to
succeed.
